---
title: ""
---

# About

My name is __*Tin Skoric*__. I am a student at the University of Vermont studying economics as an undergraduate at the Honors College. This project has been a passion of mine for a long time, and I plan to go further with it in the coming years. I hope that you have enjoyed reading through what I have put together on site, or are actively enjoy*ing* reading through it, or are even just scanning through the website. All are kindred spirits. If you are interested in this and/or want to either see what I am up to more recently, check out my [``personal website``](https://tins.page/), and if you would like to get in touch I have included some of my contact information below. Otherwise, again, I hope you have enjoyed your time looking through the site, and I wish you the best.

## Contact + Socials

[``Email``](tinskoric.work@gmail.com)
[``LinkedIn``](https://www.linkedin.com/in/tin-skoric-0b6679188)
[``GitHub``](https://github.com/tinskoric)
[``Twitter``](https://twitter.com/tinskoric)